services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruchtlabor-bot
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "${EXPOSED_IP}:${EXPOSED_PORT}:3000"
