services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: fruchtlabor-bot-dev
    restart: unless-stopped
    env_file:
      - .env.dev
    ports:
      - "${EXPOSED_IP}:${EXPOSED_PORT}:3000"
    volumes:
      - ./src:/app/src
