# dependency stage
FROM node:20-alpine AS dependency-stage
RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package*.json .
RUN npm ci


# development stage
FROM node:20-alpine as development-stage
RUN apk add --no-cache libc6-compat

ENV NODE_ENV=development

WORKDIR /app

COPY --from=dependency-stage /app/node_modules node_modules

COPY package*.json .

COPY tsconfig.json .
COPY src src

ENV INTERNAL_PORT=3000
EXPOSE 3000

CMD [ "npm", "run", "dev" ]