services:
  app:
    build: .
    container_name: fruchtlabor-bot-stage
    env_file:
      - .env.stage
    ports:
      - "${EXPOSED_PORT}:3000"
    volumes:
      - ./src:/app/src
    command: npm run dev
