services:
  <name>:
    build:
      context: <path_to_folder>
      dockerfile: Dockerfile
    container_name: <name>
    restart: unless-stopped
    env_file:
      - <path_to_folder>/.env.prod
    ports:
      - "<exposed_host>:<exposed_port>:3000"
