module.exports = {
  "Leitende Teammitglieder": [
    { name: "Admin", id: ["85"] },
    { name: "Supervisor", id: ["2487"] },
    { name: "Head-Developer", id: ["81"] },
    { name: "Head-Mod", id: ["77"] },
    { name: "Head-Designer", id: ["2537"] },
    { name: "Head-Coach", id: ["95"] },
  ],
  Teammitglieder: [
    { name: "Developer", id: ["326"] },
    { name: "Servertechniker", id: ["354"] },
    { name: "Mod", id: ["10"] },
    { name: "Inspektor", id: ["321"] },
    { name: "Recruiter", id: ["319"] },
    { name: "Teambetreuer", id: ["334"] },
    { name: "Redakteur", id: ["307"] },
    { name: "Social-Media", id: ["308"] },
    { name: "Designer", id: ["78"] },
    { name: "Cutter", id: ["2501"] },
    { name: "Event", id: ["94"] },
    { name: "Caster", id: ["82"] },
    { name: "Coach", id: ["73"] },
    { name: "Trial-Developer", id: ["2538"] },
    { name: "Trial-Mod", id: ["96"] },
    { name: "Trial-Recruiter", id: ["2539"] },
    { name: "Trial-Coach", id: ["230"] },
  ],
  Staff: [
    { name: "Berater", id: ["231"] },
    { name: "IT-Berater", id: ["328"] },
    { name: "Skin-Berater", id: ["320"] },
    { name: "Kummerkasten", id: ["2484", "2485"] },
  ],
  Supporter: [
    { name: "Head-Mod", id: ["77"] },
    { name: "Mod", id: ["10"] },
    { name: "Trial-Mod", id: ["96"] },
  ],
};
